version: '3.8'

services:
  mvp_simulation:
    image: mvp_simulation
    container_name: mvp_simulation
    environment:
      - DISPLAY
      - AUTH_COOKIE=$AUTH_COOKIE
    volumes:
      - ./src:/sim_ws/src
      - ./config:/sim_ws/config
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    # network_mode: host
    ipc: host
    privileged: false  
    stdin_open: true
    tty: true